# theme preview : https://github.com/alacritty/alacritty-theme
import = ["~/.config/alacritty/themes/themes/marine_dark.toml"]

# config : https://alacritty.org/config-alacritty.html
live_config_reload = true

[window]
opacity = 0.8
dynamic_padding = true
decorations = "buttonless"
# decorations = "Transparent"
# blur = true

[window.padding]
x = 5 # 18
y = 5 # 16

[font]
size = 16

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[colors]
# primary.background= "#001525"
primary.background = "#000505"
# primary.background= "#001005"
# cursor= {text="#ffffff", cursor="#ff0000"}
# line_indicator = { foreground = "#0000ff", background = "#ffffff" }

[bell]
animation = "Ease"
duration = 300
