-- https://github.com/moong00n/neovim-starter/blob/main/00_latest/nvim/lua/config/lsp.lua

-- local mapKey = require("utils.keyMapper").mapKey
--
-- local v = vim
-- v.api.nvim_create_autocmd("LspAttach", {
-- 	group = v.api.nvim_create_augroup("neovim-starter", { clear = true }),
-- 	callback = function(event)
-- 		local client = v.lsp.get_client_by_id(event.data.client_id)
--
-- 		-- if client:supports_method('textDocument/completion') then
-- 		--     v.lsp.completion.enable(true, client.id, event.buf, { autotrigger = true })
-- 		--
-- 		--     v.cmd("set completeopt+=noselect") -- autocompletion is buggy without this
-- 		-- end
--
-- 		-- v.diagnostic.config({
-- 		--     -- Use the default configuration
-- 		--     virtual_lines = true
-- 		--
-- 		--     -- Alternatively, customize specific options
-- 		--     -- virtual_lines = {
-- 		--     --     -- Only show virtual line diagnostics for the current cursor line
-- 		--     --     current_line = true,
-- 		--     -- },
-- 		-- })
--
-- 		mapKey("gd", ":lua v.lsp.buf.definition()<CR>")
-- 	end,
-- })
--
-- v.lsp.enable({
-- 	"lua_ls",
-- 	"tsserver",
-- 	"html",
-- 	"jsonls",
-- 	"markdown_oxide",
-- 	"pylsp",
-- 	"rust_analyzer",
-- 	"svelte",
-- 	"taplo",
-- 	"tailwindcss",
-- 	"clojure_lsp",
-- })
